name: test-workflow
on:
  push:
    branches:
      - "section/*" # * mean any words expect slash /
env:
  DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_NAME: books
jobs:
  first-job:
    container:
      image: maven:3.6.3-openjdk-17
    environment: testing # This for environment on github
    runs-on: ubuntu-latest
    steps:
      - name: print All Environments
        run: |
          echo "Database Name: ${{ env.DATABASE_NAME }} "
          echo "Username: ${{env.DATABASE_USERNAME}} "
          echo "Password: $DATABASE_PASSWORD"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Test
        run: mvn clean package
