name: test-workflow
on:
  push:
    branches:
      - "section/*" # * mean any words expect slash /
env:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: example
  DATABASE_NAME: books
  DATABASE_HOST_NAME: 127.0.0:27017
  DATABASE_PROTOCOL: mongodb
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mangodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Test
        run: mvn clean package
