name: test-workflow
on: push
env:
  DATABASE_USERNAME: ebrahim
  DATABASE_PASSWORD: 8t08IjPD2b5sOlnr
  DATABASE_NAME: books
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print Job Description
        run: echo "Execute Unit Tests"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Test
        run: mvn clean install
