name: job-output
on: workflow_dispatch
jobs:
  build-job:
    runs-on: ubuntu-latest
    outputs:
      jar-file: ${{steps.publish-jar-file.outputs.jarFile}}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Test
        run: mvn clean package
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-artifact-jar
          path: target/*.jar
      - name: publish JAR fileName
        id: publish-jar-file
        # run: find target/*jar -type f -execdir echo '::set-output name=jarFile::{}' ';' # Old way
        run: find target/*jar -type f -execdir echo 'jarFile={}' >> $GITHUB_OUTPUT ';' # New way
  deploy:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: print The file name
        run: echo ${{needs.build-job.outputs.jar-file}}
