name: condition-artifacts
on:
  push:
    branches:
      - "section/*" # * mean any words expact slash /

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, World!"
  test:
    strategy:
      matrix:
        java-version: [8, 11]
        distribution: ["temurin", "adopt"]
        architecture: [x64, x86]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Test
        id: test
        run: mvn clean test
