name: condition-artifacts
on:
  push:
    branches:
      - "section/*" # * mean any words expact slash /
jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        java-version: [8, 11]
        distribution: ["temurin", "adopt"]
        architecture: [x64, x86]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - java-version: 8
        #     distribution: adopt
        #     architecture: x86
        #     operating-system: windows-latest
        #   - java-version: 11
        #     distribution: adopt
        #     architecture: x86
        #     operating-system: windows-latest
        include:
          - java-version: 21
            # distribution: adopt
            # architecture: x86
            # operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}
      - name: Run Maven Test
        id: test
        run: echo "Run Maven Test"
