name: Reuse Workflow
on:
  push:
    branches:
      - "section/*" # * mean any words expact slash /
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the artifact
        runs: echo "Deploying....."

