name: Reusable Workflow
on:
  push:
    branches:
      - "section/*" # * mean any words expact slash /
jobs:
  test:
    # name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run Maven Test
        id: test
        run: mvn clean test
      - name: Run Maven Package
        run: mvn clean package
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-artifact-jar
          path: target/*.jar
  deploy:
    needs: test
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: spring-artifact-jar
  print-output:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print the output from the reusable workflow
        run: echo "${{needs.deploy.outputs.result-valu}}"
#    secrets:
#      DATABASE_PASSWORD: ${{secrets.DB}}
